train: \\Users\\97254\\Desktop\\Resources\\Technion\\exploratory_resaerach\\fluorovision\\data\\dataset\\images\\train
val: \\Users\\97254\\Desktop\\Resources\\Technion\\exploratory_resaerach\\fluorovision\\data\\dataset\\images\\val
names:
  0: single
  1: double
path: ''