# System constant values

IMAGE_SIZE = (300, 300)
BEAD_WIDTH_THRESHOLD = 30

# Peak detection parameters
MIN_DISTANCE = 10
NUM_PEAKS = 3
PEAK_RADIUS = 4
PEAK_INTENSITY_THRESHOLD = 1000
# clustering parameters
N_CLUSTERS = 2
FLUOROPHORE_LABEL = 1